DROP TABLE IF EXISTS county_to_county;
CREATE EXTERNAL TABLE county_to_county (
	location_code STRING,
	current_state STRING,
	current_county STRING,
	pop_1y_over_est STRING,
	pop_1y_over_moe STRING,
	current_county_nonmovers_est STRING,
	current_county_nonmovers_moe STRING,
	movers_within_current_county_est STRING,
	movers_within_current_county_moe STRING,
	movers_within_same_county_est STRING,
	movers_within_same_county_moe STRING,
	movers_dif_county_same_state_est STRING,
	movers_dif_county_same_state_moe STRING,
	movers_dif_state_current_county_est STRING,
	movers_dif_state_current_county_moe STRING,
	movers_from_abroad_est STRING,
	movers_from_abroad_moe STRING,
	prev_state_name STRING,
	prev_county_name STRING,
	prev_pop_1y_ago_est STRING,
	prev_pop_1y_ago_moe STRING,
	prev_county_nonmovers_est STRING,
	prev_county_nonmovers_moe STRING,
	prev_movers_within_us_est STRING,
	prev_movers_within_us_moe STRING,
	prev_movers_within_same_county_est STRING,
	prev_movers_within_same_county_moe STRING,
	prev_movers_dif_county_same_state_est STRING,
	prev_movers_dif_county_same_state_moe STRING,
	prev_movers_dif_state_est STRING,
	prev_movers_dif_state_moe STRING,
	pr_est STRING,
	pr_moe STRING,
	movers_within_flow_est STRING,
	movers_within_flow_moe STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE
LOCATION '/user/ahr359/final_project_files/hive_tables/county_to_county';

